version: 2
jobs:
  generate-page:
    docker:
      - image: node:14.16.1
    steps:
      - checkout
      - run:
          name: install hexo
          command: npm install hexo-cli -g
      - run:
          name: npm install
          command: npm ci
      - run:
          name: update submodule
          command: |
            echo "submodule init."
            git submodule init
            echo "submodule update."
            git submodule update
      - run:
          name: build
          command: npm run build
      - run:
          name: 部署Github Pages
          command: |
            cd public
            ls
            git init
            git config user.name "$GH_USER"
            git config user.email "$GH_EMAIL"
            git add .
            git commit -m "update"
            git push --force --quiet "https://$GH_TOKEN@$GH_REF" master
            echo 'deploy success'
workflows:
  version: 2
  build-deploy:
    jobs:
      - generate-page:
          filters:
            branches:
              only: dev
